name: Run After Checks

on:
  push:
    branches:
      - release/feat/**
      - release/fix/**

jobs:
  Quality-Gate:
    runs-on:
      - ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: ğŸ¤– Yarn install
        uses: ./.github/actions/yarn-install
        with:
          GITHUB_TOKEN: ${{secrets.CI_TOKEN}}
      - name: ğŸš¦ Qualtiy Gate
        uses: ./.github/actions/quality
      - name: ğŸ“ Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          base_branch="develop"
          
          pr_title="Pre RC ${{github.ref_name}}"
          
          pr_body="
          Automated Pre RC PR from ${{ github.ref_name }}
          source: ${{ github.ref_name }}
          target: develop"

          gh pr create --base "$base_branch" --title "$pr_title" --body "$pr_body" -l "pre-release-candidate"
      